//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpTaskkk
    {
        public int TaskId { get; set; }
        public string Title { get; set; }
        public string Descrription { get; set; }
        public string Statusemp { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual newuserr newuserr { get; set; }
    }
}
