//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class newuserr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public newuserr()
        {
            this.EmpTaskkks = new HashSet<EmpTaskkk>();
        }
    
        public int UserID { get; set; }
        public string NameEmp { get; set; }
        public string PasswordEmp { get; set; }
        public string EmailEmp { get; set; }
        public string RoleEmp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpTaskkk> EmpTaskkks { get; set; }
    }
}
